#include "screen.h"

void main() {
    // const char *message = "42 nthimoni acerdan";

    screen_buffer = (unsigned short *)VGA_ADDRESS;
    // mémoire est mappée dans le segment de mémoire à l'adresse 0xB8000
    clear_screen();
    print_str("1 Bien le bonjour gente dame comment allezBien le bonjour gente dame comment / 2 Bien le bonjour gente dame comment allezBien le bonjour gente dame comment allez/ Bien le bonjour gente dame comment allezBien le bonjour gente dame comment allez/vous ? Mea culpa 42 80 ??fffffffffffffffffAAAAAAAAAAAAAAAAAAAAAAAAAAAAffffffffffffffffffAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffffffffffffffffffffffffffffffffffffffffffffffffff42ffjattends les 80      ffffffffffffffffffffffffffffffffffffffffffffffff42fff     HEEEEYYY ffffffffff42fffaaaqq", WHITE);
    handle_keypress();
    // print_str(message, WHITE);
    // print_new_line();
    // print_str(message, RED);
    // print_new_line();
    // print_str(message, YELLOW);
    // print_new_line();
    // print_str(message, GREEN);
    // print_new_line();
}
